// Layouts / paper space: read, write back, ezdxf round trip (fixture made by test/fixtures/make_layouts.py).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { readDxf, parseDxf } from '../src/core/dxfRead.js';
import { writeDxf } from '../src/core/dxfWrite.js';
import { viewportScale } from '../src/core/layouts.js';
import { fixture, ezdxfAvailable, validateWithEzdxf, FIX } from './helpers.js';

const SCRATCH = fileURLToPath(new URL('../.cache/test-layouts/', import.meta.url));
mkdirSync(SCRATCH, { recursive: true });

/** the fixture regenerated by ezdxf when available, else the committed copy */
function source() {
  const py = ezdxfAvailable();
  if (!py) return fixture('layouts_r2000.dxf');
  const out = path.join(SCRATCH, 'gen.dxf');
  const r = spawnSync(py, [path.join(FIX, 'make_layouts.py'), out], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  return readFileSync(out);
}

function checkLayouts(doc) {
  assert.deepEqual(doc.layouts.map((l) => l.name), ['Layout1', 'Layout2']);
  for (const lo of doc.layouts) {
    const texts = lo.entities.filter((e) => e.type === 'TEXT');
    assert.deepEqual(texts.map((t) => t.text), [`TITLE ${lo.name}`]);
    const vps = lo.entities.filter((e) => e.type === 'VIEWPORT' && e.vpId !== 1);
    assert.equal(vps.length, 1, `${lo.name} viewports`);
    const vp = vps[0];
    assert.equal(Math.round(viewportScale(vp)), 50);
    assert.deepEqual([vp.c.x, vp.c.y, vp.width, vp.height], [200, 150, 300, 100]);
    assert.deepEqual([vp.viewCenter.x, vp.viewCenter.y], [500, 0]);
    assert.deepEqual(vp.frozen, ['HIDE']);
    assert.equal(lo.plot.paperW, 420); assert.equal(lo.plot.paperH, 297);
  }
  assert.equal(doc.entities.filter((e) => e.type === 'TEXT').length, 0, 'paper text stays out of model space');
  assert.equal(doc.entities.length, 2);
}

test('read: two layouts with their paper text and a 1:50 viewport each', () => {
  checkLayouts(readDxf(source()));
});

test('write: layouts, paper entities and viewports round-trip (ours and ezdxf), audit clean', () => {
  const doc = readDxf(source());
  const text = writeDxf(doc);
  checkLayouts(parseDxf(text));
  if (!ezdxfAvailable()) return;
  const file = path.join(SCRATCH, 'out.dxf');
  writeFileSync(file, text);
  const v = validateWithEzdxf(file);
  assert.equal(v.audit_errors, 0, JSON.stringify(v.audit_messages));
  const r = spawnSync(ezdxfAvailable(), ['-c', `
import ezdxf, json, sys
d = ezdxf.readfile(sys.argv[1])
out = []
for l in d.layouts:
    if l.name == 'Model': continue
    vps = [e for e in l if e.dxftype() == 'VIEWPORT' and e.dxf.id != 1]
    out.append({'name': l.name, 'texts': [e.dxf.text for e in l if e.dxftype() == 'TEXT'],
      'vps': [[v.dxf.width, v.dxf.height, v.dxf.view_height, list(v.frozen_layers)] for v in vps]})
print(json.dumps(out))`, file], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  assert.deepEqual(JSON.parse(r.stdout), ['Layout1', 'Layout2'].map((n) => ({ name: n, texts: [`TITLE ${n}`], vps: [[300, 100, 5000, ['HIDE']]] })));
});
